ALTER TABLE Stadium ADD COLUMN id integer NOT NULL;
ALTER TABLE Stadium ADD COLUMN Name varchar(100) NOT NULL;
ALTER TABLE Stadium ADD COLUMN city varchar(30) NOT NULL;
ALTER TABLE Stadium ADD COLUMN Capacity integer NOT NULL;
ALTER TABLE Stadium ADD PRIMARY KEY(id);
ALTER TABLE Stadium ADD UNIQUE (id);
ALTER TABLE game ADD CONSTRAINT FKgame98075 FOREIGN KEY (Stadiumid) REFERENCES Stadium (id);
